import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jodi
 */
public class Tugas1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Tugas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        labelDataDiri = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelTL = new javax.swing.JLabel();
        labelJK = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTL = new javax.swing.JTextField();
        txtJKKriteria = new javax.swing.JTextField();
        labelDomisili = new javax.swing.JLabel();
        txtUmurKriteria = new javax.swing.JTextField();
        labelKriteria = new javax.swing.JLabel();
        labelUmur = new javax.swing.JLabel();
        txtDomisili = new javax.swing.JTextField();
        labelJKkriteria = new javax.swing.JLabel();
        txtJK = new javax.swing.JTextField();
        txtDomisiliKriteria = new javax.swing.JTextField();
        labelDomisiliKriteria = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 255));

        judul1.setBackground(new java.awt.Color(255, 204, 255));
        judul1.setFont(new java.awt.Font("Kaufmann BT", 0, 36)); // NOI18N
        judul1.setText("Biro Jodoh Elouel");

        judul2.setFont(new java.awt.Font("HelveticaNeue BlackCond", 0, 18)); // NOI18N
        judul2.setText("\"Mengatasi masalah dengan masalah\"");

        labelDataDiri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDataDiri.setText("Data Diri");

        labelNama.setText("Nama");

        labelTL.setText("Tanggal Lahir");

        labelJK.setText("Jenis Kelamin");

        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
        });

        txtTL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTLKeyPressed(evt);
            }
        });

        txtJKKriteria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJKKriteriaKeyPressed(evt);
            }
        });

        labelDomisili.setText("Domisili");

        txtUmurKriteria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUmurKriteriaKeyPressed(evt);
            }
        });

        labelKriteria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKriteria.setText("Kriteria");

        labelUmur.setText("Umur");

        txtDomisili.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDomisiliKeyPressed(evt);
            }
        });

        labelJKkriteria.setText("Jenis Kelamin");

        txtJK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJKKeyPressed(evt);
            }
        });

        txtDomisiliKriteria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDomisiliKriteriaKeyPressed(evt);
            }
        });

        labelDomisiliKriteria.setText("Domisili");

        btnConfirm.setText("Konfirmasi");
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(judul1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(judul2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelDataDiri))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelKriteria))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNama)
                                    .addComponent(labelTL)
                                    .addComponent(labelJK)
                                    .addComponent(labelDomisili)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDomisiliKriteria)
                                    .addComponent(labelJKkriteria)
                                    .addComponent(labelUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUmurKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtJKKriteria, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTL, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDomisili, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addComponent(txtJK, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDomisiliKriteria, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(judul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul2)
                .addGap(18, 18, 18)
                .addComponent(labelDataDiri)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTL)
                    .addComponent(txtTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJK)
                    .addComponent(txtJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelKriteria)
                        .addGap(18, 18, 18)
                        .addComponent(labelUmur))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDomisili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDomisili))
                        .addGap(41, 41, 41)
                        .addComponent(txtUmurKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJKkriteria)
                    .addComponent(txtJKKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDomisiliKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDomisiliKriteria))
                .addGap(32, 32, 32)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER){
        if (txtNama.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Input tidak boleh kosong. Mohon diisi kembali.","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
            txtNama.requestFocus();
            return;
        }
        btnConfirm.requestFocus();
        }
    }//GEN-LAST:event_txtNamaKeyPressed

    private void txtTLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTLKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER){
        if (txtTL.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Input tidak boleh kosong. Mohon diisi kembali.","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
            txtTL.requestFocus();
            return;
        }
        btnConfirm.requestFocus();
        }
    }//GEN-LAST:event_txtTLKeyPressed

    private void txtJKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJKKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
        if (txtJK.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Input tidak boleh kosong. Mohon diisi kembali.","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
            txtJK.requestFocus();
            return;
        }
        btnConfirm.requestFocus();
        }
    }//GEN-LAST:event_txtJKKeyPressed

    private void txtDomisiliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDomisiliKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER){
        if (txtDomisili.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Input tidak boleh kosong. Mohon diisi kembali.","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
            txtDomisili.requestFocus();
            return;
        }
        btnConfirm.requestFocus();
        }
    }//GEN-LAST:event_txtDomisiliKeyPressed

    private void txtUmurKriteriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUmurKriteriaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
        if (txtUmurKriteria.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Input tidak boleh kosong. Mohon diisi kembali.","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
            txtUmurKriteria.requestFocus();
            return;
        }
        btnConfirm.requestFocus();
        }
    }//GEN-LAST:event_txtUmurKriteriaKeyPressed

    private void txtJKKriteriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJKKriteriaKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER){
        if (txtJKKriteria.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Input tidak boleh kosong. Mohon diisi kembali.","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
            txtJKKriteria.requestFocus();
            return;
        }
        btnConfirm.requestFocus();
        }
    }//GEN-LAST:event_txtJKKriteriaKeyPressed

    private void txtDomisiliKriteriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDomisiliKriteriaKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER){
        if (txtDomisiliKriteria.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Input tidak boleh kosong. Mohon diisi kembali.","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
            txtDomisiliKriteria.requestFocus();
            return;
        }
        btnConfirm.requestFocus();
        }
    }//GEN-LAST:event_txtDomisiliKriteriaKeyPressed

    private void btnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseClicked
    String Nama = txtNama.getText();
    String TL = txtTL.getText();
    String JK = txtJK.getText();
    String Domisili = txtDomisili.getText();
    String UmurKriteria = txtUmurKriteria.getText();
    String JKKriteria = txtJKKriteria.getText();
    String DomisiliKriteria = txtDomisiliKriteria.getText();
    JOptionPane.showMessageDialog(this,"Data Diri: \n\nNama : "+Nama+"\nTL :"+TL+"\n Kelamin :"+JK+"\n Domisili :"+Domisili+"\n\nKriteria yang dicari:\n\n Umur :"+UmurKriteria+"\n Kelamin: "+JKKriteria+"\n Domisili: "+DomisiliKriteria);
    }//GEN-LAST:event_btnConfirmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel labelDataDiri;
    private javax.swing.JLabel labelDomisili;
    private javax.swing.JLabel labelDomisiliKriteria;
    private javax.swing.JLabel labelJK;
    private javax.swing.JLabel labelJKkriteria;
    private javax.swing.JLabel labelKriteria;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTL;
    private javax.swing.JLabel labelUmur;
    private javax.swing.JTextField txtDomisili;
    private javax.swing.JTextField txtDomisiliKriteria;
    private javax.swing.JTextField txtJK;
    private javax.swing.JTextField txtJKKriteria;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTL;
    private javax.swing.JTextField txtUmurKriteria;
    // End of variables declaration//GEN-END:variables
}
